version: "1.0"
services:
  postgres:
    image: postgres:16.0-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clothes_store
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_db: