"""empty message

Revision ID: 4ba996b93b79
Revises: 3f774d60dd8c
Create Date: 2024-09-06 09:15:29.367114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba996b93b79'
down_revision: Union[str, None] = '3f774d60dd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
