"""empty message

Revision ID: b87dea6e4ffd
Revises: 5674034542e3
Create Date: 2024-07-30 22:25:53.602321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87dea6e4ffd'
down_revision: Union[str, None] = '5674034542e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('name', sa.String(length=30), nullable=True))
    op.drop_column('employee', 'last_name')
    op.drop_column('employee', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('employee', 'name')
    # ### end Alembic commands ###
