"""empty message

Revision ID: d1e542cf8cd8
Revises: df85ff1b1fd0
Create Date: 2024-08-03 09:21:31.879976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e542cf8cd8'
down_revision: Union[str, None] = 'df85ff1b1fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'address')
    # ### end Alembic commands ###
