"""empty message

Revision ID: df85ff1b1fd0
Revises: b87dea6e4ffd
Create Date: 2024-08-01 22:40:52.765621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df85ff1b1fd0'
down_revision: Union[str, None] = 'b87dea6e4ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
