"""empty message

Revision ID: f4fa87ac1ac8
Revises: eea9258ef38b
Create Date: 2024-07-15 06:38:02.442204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fa87ac1ac8'
down_revision: Union[str, None] = 'eea9258ef38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_details', sa.Column('inventory_id', sa.Integer(), nullable=True))
    op.drop_constraint('invoice_details_product_id_fkey', 'invoice_details', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_details', 'inventory', ['inventory_id'], ['id'])
    op.drop_column('invoice_details', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_details', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoice_details', type_='foreignkey')
    op.create_foreign_key('invoice_details_product_id_fkey', 'invoice_details', 'product', ['product_id'], ['id'])
    op.drop_column('invoice_details', 'inventory_id')
    # ### end Alembic commands ###
